[system]
compatible=PscgSecureOS
bootloader=grub
grubenv=/efi/EFI/Boot/grubenv
mountprefix=/run/rauc
statusfile=/data/rauc.status

[handlers]
# Map the script specifically to the "post-install" event
post-install=/etc/rauc/hooks.sh

# Note: they call it keyring, but it is not the Linux keyring you may know
[keyring]
path=/etc/rauc/keyring.pem

# ----------------------------------------------------------------------
# SLOT A
# ----------------------------------------------------------------------
[slot.rootfs.0]
device=/dev/disk/by-partlabel/ROOTFS_A
type=raw
bootname=A

[slot.verity_hash.0]
device=/dev/disk/by-partlabel/DMVERITY_HASH_A
type=raw
parent=rootfs.0

[slot.boot.0]
device=/dev/disk/by-partlabel/BOOT_A
type=ext4
parent=rootfs.0

# ----------------------------------------------------------------------
# SLOT B
# ----------------------------------------------------------------------
[slot.rootfs.1]
device=/dev/disk/by-partlabel/ROOTFS_B
type=raw
bootname=B

[slot.verity_hash.1]
device=/dev/disk/by-partlabel/DMVERITY_HASH_B
type=raw
parent=rootfs.1

[slot.boot.1]
device=/dev/disk/by-partlabel/BOOT_B
type=ext4
parent=rootfs.1
